controllers:
    resource: ../src/Controller/
    type: annotation
client:
  resource: ../src/CoreAPI/Client/Application/
  type: annotation
kernel:
    resource: ../src/Kernel.php
    type: annotation
